### PR TITLE
serde: add #concat method

### PR DESCRIPTION
**Pull request by kenhys**
feed_each and to_msgpack can handle wired msgpack but to_msgpack
only writes each msgpack blob on demand.

There is no public interface to concatenate wired msgpack in a bunch.

### CODE REVIEW

**Comment by kenhys** [comment]
FIXME:  SEGV for gauge and untyped.

**Comment by cosmo0920** [comment]
I tested this PR with the following script:

```ruby
require 'cmetrics'

@gauge = CMetrics::Gauge.new
@gauge.create("kubernetes", "network", "load", "Network load", ["hostname", "app"])
@gauge.set 2.0
@gauge.inc(["localhost", "cmetrics"])
@gauge.add(10, ["localhost", "test"])
@counter = CMetrics::Counter.new
@counter.create("kubernetes", "network", "load", "Network load", ["hostname", "app"])
@counter.inc
@counter.inc(["localhost", "cmetrics"])
@counter.inc(["localhost", "cmetrics"])
@counter.add(10.55, ["localhost", "test"])
@counter2 = CMetrics::Counter.new
@counter2.create("cmt", "labels", "test", "Static labels test", ["host", "app"])
@counter2.inc
@counter2.inc(["calyptia.com", "cmetrics"])
@counter2.inc(["calyptia.com", "cmetrics"])
@counter2.add_label("dev", "Calyptia")
@counter2.add_label("lang", "C")
@untyped = CMetrics::Untyped.new
@untyped.create("cmt", "labels", "untyped", "untyped metrics", ["hostname", "app"])
@untyped.set(1)
@untyped.set(12, ["localhost", "untyped"])
buffer_array = [@gauge.to_msgpack]
@wired_buffer = buffer_array.concat([@counter.to_msgpack, @counter2.to_msgpack]).join
@serde = CMetrics::Serde.new

puts "-----Concatenate Gauge/Counter/Untyped-----"
[@gauge, @counter, @counter2, @untyped].map do |cmetric|
  @serde.concat(cmetric)
  puts @serde.to_prometheus
  puts @serde.metrics
end
```

```console
-----Concatenate Gauge/Counter/Untyped-----
{"namespace"=>"kubernetes", "subsystem"=>"network", "name"=>"load", "description"=>"Network load", "value"=>2.0, "timestamp"=>1631764718.2720091}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"cmetrics"}, "name"=>"load", "description"=>"Network load", "value"=>1.0, "timestamp"=>1631764718.2720156}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"test"}, "name"=>"load", "description"=>"Network load", "value"=>10.0, "timestamp"=>1631764718.2720206}
{"namespace"=>"kubernetes", "subsystem"=>"network", "name"=>"load", "description"=>"Network load", "value"=>1.0, "timestamp"=>1631764718.272029}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"cmetrics"}, "name"=>"load", "description"=>"Network load", "value"=>2.0, "timestamp"=>1631764718.272031}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"test"}, "name"=>"load", "description"=>"Network load", "value"=>10.55, "timestamp"=>1631764718.272032}
{"namespace"=>"kubernetes", "subsystem"=>"network", "name"=>"load", "description"=>"Network load", "value"=>2.0, "timestamp"=>1631764718.2720091}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"cmetrics"}, "name"=>"load", "description"=>"Network load", "value"=>1.0, "timestamp"=>1631764718.2720156}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"test"}, "name"=>"load", "description"=>"Network load", "value"=>10.0, "timestamp"=>1631764718.2720206}
{"namespace"=>"kubernetes", "subsystem"=>"network", "name"=>"load", "description"=>"Network load", "value"=>1.0, "timestamp"=>1631764718.272029}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"cmetrics"}, "name"=>"load", "description"=>"Network load", "value"=>2.0, "timestamp"=>1631764718.272031}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"test"}, "name"=>"load", "description"=>"Network load", "value"=>10.55, "timestamp"=>1631764718.272032}
{"namespace"=>"cmt", "subsystem"=>"labels", "name"=>"test", "description"=>"Static labels test", "value"=>1.0, "timestamp"=>1631764718.2720366}
{"namespace"=>"cmt", "subsystem"=>"labels", "labels"=>{"host"=>"calyptia.com", "app"=>"cmetrics"}, "name"=>"test", "description"=>"Static labels test", "value"=>2.0, "timestamp"=>1631764718.2720377}
{"namespace"=>"kubernetes", "subsystem"=>"network", "name"=>"load", "description"=>"Network load", "value"=>2.0, "timestamp"=>1631764718.2720091}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"cmetrics"}, "name"=>"load", "description"=>"Network load", "value"=>1.0, "timestamp"=>1631764718.2720156}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"test"}, "name"=>"load", "description"=>"Network load", "value"=>10.0, "timestamp"=>1631764718.2720206}
{"namespace"=>"kubernetes", "subsystem"=>"network", "name"=>"load", "description"=>"Network load", "value"=>1.0, "timestamp"=>1631764718.272029}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"cmetrics"}, "name"=>"load", "description"=>"Network load", "value"=>2.0, "timestamp"=>1631764718.272031}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"test"}, "name"=>"load", "description"=>"Network load", "value"=>10.55, "timestamp"=>1631764718.272032}
{"namespace"=>"cmt", "subsystem"=>"labels", "name"=>"test", "description"=>"Static labels test", "value"=>1.0, "timestamp"=>1631764718.2720366}
{"namespace"=>"cmt", "subsystem"=>"labels", "labels"=>{"host"=>"calyptia.com", "app"=>"cmetrics"}, "name"=>"test", "description"=>"Static labels test", "value"=>2.0, "timestamp"=>1631764718.2720377}
{"namespace"=>"kubernetes", "subsystem"=>"network", "name"=>"load", "description"=>"Network load", "value"=>2.0, "timestamp"=>1631764718.2720091}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"cmetrics"}, "name"=>"load", "description"=>"Network load", "value"=>1.0, "timestamp"=>1631764718.2720156}
{"namespace"=>"kubernetes", "subsystem"=>"network", "labels"=>{"hostname"=>"localhost", "app"=>"test"}, "name"=>"load", "description"=>"Network load", "value"=>10.0, "timestamp"=>1631764718.2720206}
{"namespace"=>"cmt", "subsystem"=>"labels", "name"=>"untyped", "description"=>"untyped metrics", "value"=>1.0, "timestamp"=>1631764718.272043}
{"namespace"=>"cmt", "subsystem"=>"labels", "labels"=>{"hostname"=>"localhost", "app"=>"untyped"}, "name"=>"untyped", "description"=>"untyped metrics", "value"=>12.0, "timestamp"=>1631764718.2720437}
```

Good job! :+1: :relaxed:

**Comment by cosmo0920** [comment]
I kicked GitHub Actions workflows for testing....

**Comment by cosmo0920** [comment]
SEGV is still occurred on your box, @kenhys?

**Comment by kenhys** [comment]
As far as I know, SEGV issue was solved.

**Comment by kenhys** [comment]
One concern is:
Is it reasonable to assume that msgpack decoder is initialized when directly #concat is called?

**Comment by cosmo0920** [comment]
> Is it reasonable to assume that msgpack decoder is initialized when directly #concat is called?

Sorry, I'm not fully understand your question. What kind of scenario do you assume?

**Comment by cosmo0920** [comment]
Ah, I got it.

> Is it reasonable to assume that msgpack decoder is initialized when directly #concat is called?

This shouldn't be reasonable.
Before calling `#concat`, you should just translate serde context via `#from_smgpack` or `#feed_each`.

**Comment by kenhys** [comment]
For supporting the following case,

```
  @counter = CMetrics::Counter.new
  @counter.set(10)
  @serde = CMetrics::Serde.new
  @serde.concat(@counter) #=> Directly append @counter
```

In the implementation of #concat, internally convert CMetrics into msgpack explicitly.
It is required to call cmt_cat without SEGV, but I'm not sure that it is proper approach.(though I know it can solve the issue)

**Comment by kenhys** [comment]
You mean:

```
# not acceptable
@counter = CMetrics::Counter.new
@counter.set(10)
@serde = CMetrics::Serde.new
@serde.concat(@counter) #=> should raise an error
```

```
# only acceptable
@counter = CMetrics::Counter.new
@counter.set(10)
@serde = CMetrics::Serde.new
@serde.from_msgpack(@counter.to_msgpack)
@serde.concat(...)
```

**Comment by cosmo0920** [comment]
> In the implementation of #concat, internally convert CMetrics into msgpack explicitly.
> It is required to call cmt_cat without SEGV(cmetricsSerde->instance == NULL), but I'm not sure that it is proper approach.(though I know it can solve the issue)

How about plugging with `cmt_create()` when `cmetricsSerde->instance == NULL` case?
The below patch doesn't cause SEGV when it is NULL>

```diff
diff --git a/ext/cmetrics/cmetrics_serde.c b/ext/cmetrics/cmetrics_serde.c
index cd446b6..29dc239 100644
--- a/ext/cmetrics/cmetrics_serde.c
+++ b/ext/cmetrics/cmetrics_serde.c
@@ -180,40 +180,26 @@ rb_cmetrics_serde_concat_metric(VALUE self, VALUE rb_data)
     struct CMetricsCounter* cmetricsCounter = NULL;
     struct CMetricsGauge* cmetricsGauge = NULL;
     struct CMetricsUntyped* cmetricsUntyped = NULL;
-    struct cmt *cmt = NULL;
-    VALUE rb_cmetrics_counter_type;
-    VALUE rb_msgpack_buffer;
-    VALUE rb_msgpack_size;
-    int ret = 0;
-    size_t offset = 0;
 
     TypedData_Get_Struct(
             self, struct CMetricsSerde, &rb_cmetrics_serde_type, cmetricsSerde);
 
     if (!NIL_P(rb_data)) {
         if (cmetricsSerde->instance == NULL) {
-            rb_msgpack_buffer = rb_funcall(rb_data, rb_intern("to_msgpack"), 0, 0);
-            rb_msgpack_size = rb_funcall(rb_msgpack_buffer, rb_intern("size"), 0, 0);
-            ret = cmt_decode_msgpack_create(&cmt, StringValuePtr(rb_msgpack_buffer), NUM2INT(rb_msgpack_size), &offset);
-            if (ret == 0) {
-                cmetricsSerde->instance = cmt;
-                cmetricsSerde->unpack_msgpack_offset = offset;
-            } else {
-                rb_raise(rb_eRuntimeError, "failed to store given argument into msgpack.");
-            }
+            cmetricsSerde->instance = cmt_create();
+        }
+
+        if (rb_obj_is_kind_of(rb_data, rb_cCounter)) {
+            cmetricsCounter = (struct CMetricsCounter *)cmetrics_counter_get_ptr(rb_data);
+            cmt_cat(cmetricsSerde->instance, cmetricsCounter->instance);
+        } else if (rb_obj_is_kind_of(rb_data, rb_cGauge)) {
+            cmetricsGauge = (struct CMetricsGauge *)cmetrics_gauge_get_ptr(rb_data);
+            cmt_cat(cmetricsSerde->instance, cmetricsGauge->instance);
+        } else if (rb_obj_is_kind_of(rb_data, rb_cUntyped)) {
+            cmetricsUntyped = (struct CMetricsUntyped *)cmetrics_untyped_get_ptr(rb_data);
+            cmt_cat(cmetricsSerde->instance, cmetricsUntyped->instance);
         } else {
-            if (rb_obj_is_kind_of(rb_data, rb_cCounter)) {
-                cmetricsCounter = (struct CMetricsCounter *)cmetrics_counter_get_ptr(rb_data);
-                cmt_cat(cmetricsSerde->instance, cmetricsCounter->instance);
-            } else if (rb_obj_is_kind_of(rb_data, rb_cGauge)) {
-                cmetricsGauge = (struct CMetricsGauge *)cmetrics_gauge_get_ptr(rb_data);
-                cmt_cat(cmetricsSerde->instance, cmetricsGauge->instance);
-            } else if (rb_obj_is_kind_of(rb_data, rb_cUntyped)) {
-                cmetricsUntyped = (struct CMetricsUntyped *)cmetrics_untyped_get_ptr(rb_data);
-                cmt_cat(cmetricsSerde->instance, cmetricsUntyped->instance);
-            } else {
-                rb_raise(rb_eArgError, "specified type of instance is not supported.");
-            }
+            rb_raise(rb_eArgError, "specified type of instance is not supported.");
         }
     } else {
         rb_raise(rb_eArgError, "nil is not valid value for concatenating");
```

**Comment by kenhys** [comment]
Ah, it is more sophisticated.

**Comment by cosmo0920** [comment]
> In the implementation of #concat, internally convert CMetrics into msgpack explicitly.
> It is required to call cmt_cat without SEGV(cmetricsSerde->instance == NULL), but I'm not sure that it is proper approach.(though I know it can solve the issue)

```c
        if (cmetricsSerde->instance == NULL) {
            cmetricsSerde->instance = cmt_create();
        }
```

Using `cmt_create()` is enough.

**Comment by kenhys** [comment]
@cosmo0920 Thanks!

**Review by cosmo0920 — APPROVED** [review]
Seems very good. Great job! :+1:

**Comment by kenhys** [comment]
@cosmo0920  could you release as a new version, please?

**Comment by cosmo0920** [comment]
Released as v0.2.2:
https://rubygems.org/gems/cmetrics/versions/0.2.2

**Comment by kenhys** [comment]
@cosmo0920 

Thanks!

**Pull request merged**
